# Generated by Django 4.2.2 on 2023-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendsgroups",
            name="desc",
            field=models.TextField(
                default="", max_length=300, null=True, verbose_name="组群简介"
            ),
        ),
    ]
