# Generated by Django 4.2.2 on 2023-06-27 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="", max_length=500, null=True, verbose_name="文本内容"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("1", "文本"), ("2", "图片"), ("3", "文件")],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "组群消息",
                "verbose_name_plural": "组群消息",
            },
        ),
        migrations.CreateModel(
            name="MessagesFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="user_message_file/%Y/%m", verbose_name="用户消息文件"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户文件",
                "verbose_name_plural": "用户文件",
            },
        ),
        migrations.CreateModel(
            name="MessagesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="user_message_image/%Y/%m", verbose_name="用户消息图片"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户图片",
                "verbose_name_plural": "用户图片",
            },
        ),
        migrations.CreateModel(
            name="UserDynamic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                ("content", models.CharField(max_length=300, verbose_name="动态文章")),
                ("likes", models.IntegerField(default=0, verbose_name="点赞数")),
            ],
            options={
                "verbose_name": "用户动态",
                "verbose_name_plural": "用户动态",
            },
        ),
        migrations.CreateModel(
            name="UserDynamicComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                ("comment", models.CharField(max_length=300, verbose_name="评论内容")),
            ],
            options={
                "verbose_name": "用户动态评论",
                "verbose_name_plural": "用户动态评论",
            },
        ),
        migrations.CreateModel(
            name="UserDynamicImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="",
                        null=True,
                        upload_to="dynamic_image/%Y/%m",
                        verbose_name="动态图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户动态图片",
                "verbose_name_plural": "用户动态图片",
            },
        ),
        migrations.CreateModel(
            name="UserDynamicLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户动态图片",
                "verbose_name_plural": "用户动态图片",
            },
        ),
        migrations.CreateModel(
            name="UserMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="", max_length=500, null=True, verbose_name="文本内容"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("1", "文本"), ("2", "图片"), ("3", "文件")],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户消息",
                "verbose_name_plural": "用户消息",
            },
        ),
    ]
