# Generated by Django 4.2.2 on 2023-06-27 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("message", "0001_initial"),
        ("relationship", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessages",
            name="user_reserve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reserve",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收方用户",
            ),
        ),
        migrations.AddField(
            model_name="usermessages",
            name="user_send",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_send",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送方用户",
            ),
        ),
        migrations.AddField(
            model_name="userdynamiclikes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AddField(
            model_name="userdynamiclikes",
            name="user_dynamic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.userdynamic",
                verbose_name="用户动态",
            ),
        ),
        migrations.AddField(
            model_name="userdynamicimage",
            name="user_dynamic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.userdynamic",
                verbose_name="用户动态",
            ),
        ),
        migrations.AddField(
            model_name="userdynamiccomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AddField(
            model_name="userdynamiccomment",
            name="user_dynamic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.userdynamic",
                verbose_name="用户动态",
            ),
        ),
        migrations.AddField(
            model_name="userdynamic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="messagesimage",
            name="group_messages",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="relationship.friendsgroups",
                verbose_name="组群消息",
            ),
        ),
        migrations.AddField(
            model_name="messagesimage",
            name="user_messages",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户消息",
            ),
        ),
        migrations.AddField(
            model_name="messagesfile",
            name="group_messages",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="relationship.friendsgroups",
                verbose_name="组群消息",
            ),
        ),
        migrations.AddField(
            model_name="messagesfile",
            name="user_messages",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户消息",
            ),
        ),
        migrations.AddField(
            model_name="groupmessages",
            name="user_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="relationship.friendsgroups",
                verbose_name="接收方组群",
            ),
        ),
        migrations.AddField(
            model_name="groupmessages",
            name="user_send",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送方用户",
            ),
        ),
    ]
