# Generated by Django 4.2.2 on 2023-06-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdynamic",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="动态标题"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdynamic",
            name="content",
            field=models.TextField(max_length=300, verbose_name="动态正文"),
        ),
    ]
