# Generated by Django 4.2.2 on 2023-06-27 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0004_alter_userdynamic_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdynamiccomment",
            options={"verbose_name": "动态评论", "verbose_name_plural": "动态评论"},
        ),
        migrations.AlterModelOptions(
            name="userdynamiclikes",
            options={"verbose_name": "动态点赞", "verbose_name_plural": "动态点赞"},
        ),
        migrations.AlterField(
            model_name="userdynamiccomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论用户",
            ),
        ),
    ]
