# Generated by Django 4.2.2 on 2023-06-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relationship", "0003_alter_friendsgroups_desc"),
        ("message", "0006_alter_usermessages_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdynamicimage",
            options={"verbose_name": "动态图片", "verbose_name_plural": "动态图片"},
        ),
        migrations.AlterField(
            model_name="messagesimage",
            name="group_messages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="relationship.friendsgroups",
                verbose_name="组群消息",
            ),
        ),
        migrations.AlterField(
            model_name="messagesimage",
            name="user_messages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户消息",
            ),
        ),
    ]
