# Generated by Django 4.2.2 on 2023-06-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relationship", "0003_alter_friendsgroups_desc"),
        ("message", "0007_alter_userdynamicimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagesfile",
            name="group_messages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="relationship.friendsgroups",
                verbose_name="组群消息",
            ),
        ),
        migrations.AlterField(
            model_name="messagesfile",
            name="user_messages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户消息",
            ),
        ),
    ]
