# Generated by Django 4.2.2 on 2023-06-27 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0008_alter_messagesfile_group_messages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMessagesFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="user_message_file/%Y/%m", verbose_name="用户消息文件"
                    ),
                ),
                (
                    "user_messages",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.usermessages",
                        verbose_name="用户消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户消息文件",
                "verbose_name_plural": "用户消息文件",
            },
        ),
        migrations.CreateModel(
            name="UserMessagesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="user_message_image/%Y/%m", verbose_name="用户消息图片"
                    ),
                ),
                (
                    "user_messages",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.usermessages",
                        verbose_name="用户消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户消息图片",
                "verbose_name_plural": "用户消息图片",
            },
        ),
        migrations.RemoveField(
            model_name="messagesimage",
            name="group_messages",
        ),
        migrations.RemoveField(
            model_name="messagesimage",
            name="user_messages",
        ),
        migrations.DeleteModel(
            name="MessagesFile",
        ),
        migrations.DeleteModel(
            name="MessagesImage",
        ),
    ]
