# Generated by Django 4.2.2 on 2023-06-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0010_alter_usermessagesfile_user_messages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessagesfile",
            name="user_messages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupmessagesimage",
            name="user_messages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usermessagesfile",
            name="user_messages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usermessagesimage",
            name="user_messages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.usermessages",
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
    ]
