# Generated by Django 4.2.2 on 2023-06-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0012_alter_usermessages_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessagesfile",
            name="group_messages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.groupmessages",
                verbose_name="组",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupmessagesimage",
            name="group_messages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.groupmessages",
                verbose_name="组",
            ),
            preserve_default=False,
        ),
    ]
