# Generated by Django 4.2.2 on 2023-06-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0013_groupmessagesfile_group_messages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessages",
            name="content",
            field=models.TextField(
                default="", max_length=500, null=True, verbose_name="文本内容"
            ),
        ),
    ]
