# Generated by Django 4.2.2 on 2023-06-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0014_alter_groupmessages_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessagesfile",
            name="user_messages",
        ),
        migrations.RemoveField(
            model_name="groupmessagesimage",
            name="user_messages",
        ),
    ]
